INSERT INTO taxiapp.locations (location_name) VALUES ('Оболонський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Деснянський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Дніпровський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Дарницький');
INSERT INTO taxiapp.locations (location_name) VALUES ('Голосіївський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Печерський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Солом\'янський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Шевченківський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Святошинський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Подільський');

INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 1, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 2, '28');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 3, '20');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 4, '34');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 5, '31');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 6, '23');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 7, '15');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 8, '10');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 9, '15');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 10, '6');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 2, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 3, '17');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 4, '26');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 5, '34');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 6, '25');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 7, '32');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 8, '30');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 9, '39');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 10, '29');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 3, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 4, '19');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 5, '17');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 6, '8');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 7, '15');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 8, '12');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 9, '23');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 10, '15');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (4, 4, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (4, 5, '19');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (4, 6, '18');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (4, 7, '19');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (4, 8, '24');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (4, 9, '30');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (4, 10, '27');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (5, 5, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (5, 6, '14');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (5, 7, '21');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (5, 8, '23');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (5, 9, '26');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (5, 10, '25');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (6, 6, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (6, 7, '10');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (6, 8, '12');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (6, 9, '18');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (6, 10, '14');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (7, 7, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (7, 8, '6');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (7, 9, '12');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (7, 10, '11');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (8, 8, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (8, 9, '10');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (8, 10, '9');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (9, 9, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (9, 10, '12');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (10, 10, '1');

INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Beige Suzuki Maruti 800', '50', 1, 1, 2);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Blue Hyundai i10', '50', 1, 1, 2);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Black Honda Accord', '75', 1, 1, 4);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('White Sobol Bargusin', '100', 1, 1, 6);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Red Honda CR-Z', '150', 1, 2, 2);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Black Toyota Camry', '175', 1, 2, 4);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Silver Audi A5', '175', 1, 2, 4);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('White Shkoda Octavia', '175', 1, 2, 4);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('White Fiat Scudo', '200', 1, 2, 6);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Silver Opel Astra G', '200', 1, 2, 6);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Red Smart Roadster', '250', 1, 3, 2);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Black Mercedes Benz', '275', 1, 3, 4);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Silver BMW X7', '300', 1, 3, 6);
